# prefixキーをC-tに変更
set-option -g prefix C-t
unbind C-b

# キーストロークのディレイを減らす
set -sg escape-time 1

# ウィンドウのインデックスを1から始める
set -g base-index 1

# ペインのインデックスを1から始める
setw -g pane-base-index 1

# ~/.tmux.confをリロードするkeybind
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# status bar
## left status bar
set -g status-left-length 40
## set -g status-left "#[fg=green]Session: #S #[fg=yellow]#I #[fg=cyan]#P"
set -g status-left "#[fg=colour108,bg=colour237,bold] [#S:#I:#P] "
## right status bar
set -g status-right "#[fg=cyan][%Y-%m-%d(%a) %H:%M]"
## リフレッシュの間隔を設定する(デフォルト 15秒)
set -g status-interval 60
## ウィンドウリストの位置を中心寄せにする
set -g status-justify centre
## ヴィジュアルノーティフィケーションを有効にする
setw -g monitor-activity on
set -g visual-activity on

set -g bell-action none
## ステータスバーを上部に表示する
set -g status-position top

set -g status-style bg="black"
set -g status-style fg="white"
set -g message-style fg="white"
set -g message-style bg="red"
set -g pane-active-border-style fg="cyan"
set -g pane-active-border-style bg="black"
setw -g window-status-current-style fg="blue"

set-window-option -g mode-style bg="white"
set-window-option -g mode-style fg="colour166" #orange
set-window-option -g window-status-style fg="white"
set-window-option -g window-status-style bg="black"
set-window-option -g window-status-current-style bg="black"
set-window-option -g window-status-current-style fg="green"

# Option
set-window-option -g automatic-rename on
# set-option -g mouse-select-pane on
#setw -g mode on
set-option -g base-index 0

# KeyBindings
unbind l
unbind ^C

bind t next-window
bind C-t last-pane
bind -r C-l next-layout
bind 'c' neww -c "#{pane_current_path}"

# session の作成, 移動
bind C-c new-session
bind C-n switch-client -n
bind C-p switch-client -p

bind M-a choose-tree
bind M-e choose-session
bind M-w choose-tree -w

# | でペインを縦に分割
bind | split-window -h -c "#{pane_current_path}"
# - でペインを横に分割
bind - split-window -v -c "#{pane_current_path}"

# 複数ペイン同時編集
bind e setw synchronize-panes on
bind E setw synchronize-panes off

bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1
bind -r C-j resize-pane -D 1
bind -r C-k resize-pane -U 1
bind -r s swap-pane -U

bind w kill-pane
bind W kill-window

bind i display-panes

# copy-mode関連
unbind ^"["
bind -r ^"[" copy-mode
unbind ^]
bind -r ^] paste-buffer
# vで矩形選択の切り替え
bind -T copy-mode v send-keys -X rectangle-toggle

bind -T copy-mode M-w send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind -T copy-mode C-w send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm:colors=256'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Workaround for LSOpenURLsWithRole error on Mac
# set-option -g default-command "which reattach-to-user-namespace >/dev/null 2>&1 && reattach-to-user-namespace -l ${SHELL} || ${SHELL}"
set-option -g default-command "reattach-to-user-namespace -l zsh"

set-window-option -g mode-keys emacs

# set -g terminal-overrides 'xterm*:smcup@:rmcup@'

set-option -g history-limit 10000