[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "Moralerspace Argon NF"
style = "Regular"

[font.offset]
x = 1
